server:
  port: 8000
spring:
  datasource:
    url: jdbc:mysql://211.69.142.119:3306/achievement?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=GMT%2B8
    username: achievement
    password: Feidian@520
    driver-class-name: com.mysql.cj.jdbc.Driver

  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 250MB
  jackson:
    time-zone: GMT+8


mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml

file:
  path: /root/achievement/file/

logging:
  path: /root/achievement/log/


